<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h3>Autenticação</h3>

    <form action="/admin/login" method="post">
        <input name="email" type="email" placeholder="email">
        <input name="password" type="password" placeholder="senha">
        <input type="submit" value="Salvar">
    </form>
</body>

</html>