<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h3>Página: {{ page.title }}</h3>

    <form action="/admin/pages/edit/{{ page.id }}" method="post">
        <input name="title" type="text" placeholder="title" value="{{ page.title }}">
        <textarea name="body">{{ page.body }}</textarea>
        <input type="submit" value="Salvar">
    </form>
</body>

</html>