<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>

<body>

    <h3>Usuário: {{ user.email }}</h3>

    <form action="/admin/users/edit/{{ user.id }}" method="post">
        <input name="email" type="email" placeholder="email" value="{{ user.email }}">
        <input name="password" type="password" placeholder="senha" value="">
        <input type="submit" value="Salvar">
    </form>
</body>

</html>