<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>

<body>
    <table class="">
        <thead>
            <tr>
                <th>id</th>
                <th>nome</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="/admin/users/{{user.id}}">ver</a>
                    <a href="/admin/users/edit/{{user.id}}">editar</a>
                    <form action="/admin/users/delete/{{ user.id }}" method="post" style="display:inline-block">
                        <input type="submit" value="remover">
                    </form>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="3">Nenhum registro</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>